### ISSUE TITLE
Method signature compatibility error in Clickatell\ClickatellEvent::getMessageCharge()

### ISSUE THREAD

**Issue by boteeka** [arcturial/clickatell#17]
Declaration of Clickatell\ClickatellEvent::getMessageCharge() must be compatible with Clickatell\TransportInterface::getMessageCharge($msgId, $cliMsgId = false) in file ...../arcturial/clickatell/src/ClickatellEvent.php on line 28

**Comment by boteeka** [comment]
PR: #18

**Comment by arcturial** [comment]
Thanks for the contribution. As for the Symfony dependencies, I think I will move them into the "suggest" options. Not everyone will use this library with Symfony. It should really be split into a different package (eg. clickatell-symfony-bundle), but it feels like a waste for 3 files at this moment.

**Comment by boteeka** [comment]
I agree that the Symfony dependencies are sort of optional, so moving code that needs them to a different package seems to be a good idea.

I only added them, because in my opinion if code references some other code, then that should be present as well 😉
