### ISSUE TITLE
Special characters get mangled

### ISSUE THREAD

**Issue by lahdekorpi** [arcturial/clickatell#19]
Sending UTF-8 "ä" results in "A¤".

**Comment by lahdekorpi** [comment]
However, the message report page shows the string correctly:
![screenshot 2015-12-02 12 10 20](https://cloud.githubusercontent.com/assets/570545/11528166/bdbf44b2-98ed-11e5-9699-3fb12c2efeac.png)

A problem with their servers instead of the library?

**Comment by arcturial** [comment]
Where do you see the incorrect character? Is it on some report in the Developers Central or a return from the library.

**Comment by lahdekorpi** [comment]
In the receiving phone itself. The Developers Central shows it correctly, as shown in the screenshot above.
I contacted Clickatell about this to see if it's a problem on their end.
Their system should be the one doing the UTF-8 to GSM 03.38 encoding on their end, not the client, correct?

**Comment by arcturial** [comment]
Can you maybe provide me with the message ID. I can check if it was passed and recorded with the correct information or escalate it to Clickatell support.

**Comment by lahdekorpi** [comment]
Ticket #02989178

MESSAGE CONTENT
"Tässä on vain testi."

API Message ID
87c6ad45a5e85046b6fcfcc6507af11d

API ID
3575021 (REST)

But the phone receives it with "TA¤ssA¤ on vain testi."

**Comment by arcturial** [comment]
Did you send the message with "unicode => 1" as an extra parameter?

**Comment by lahdekorpi** [comment]
No, I don't want to waste characters for unicode, because the only special characters I'm needing are Ä, ä, Ö and ö.
Those are in the GSM 03.38.

Something like "Tässä on vain testi." should be just fine to send without unicode.

**Comment by arcturial** [comment]
Ok, that could be an API limitation. I will follow up tomorrow morning and let you know (assuming the support staff has not already responded to your case). I don't think it's related to the library, but I will keep it open until I can gather more information.

**Comment by lahdekorpi** [comment]
Thanks a lot for taking a look at this!
Cosidering that the Developers Central is showing it correctly, I doubt there is anything wrong with the library itself, it's just passing along the UTF-8 text as it should.

**Comment by arcturial** [comment]
Hi

Followed up with support, the ticket has been escalated for the engine team to investigate. I am going to resolve the ticket here so it can be tracked on the official case number.

**Comment by lahdekorpi** [comment]
Thanks again, Chris for helping!
