### ISSUE TITLE
ClickatellRest - Response is never returned on error

### ISSUE THREAD

**Issue by webspecnick** [arcturial/clickatell#25]
Problem:
When using ClickatellRest the method `sendMessage` returns an empty array when there's an error, instead of the error itself.

Expected Behavior:
The function should return the error information when there's an error.

Actual Behavior:
Errors return an empty array

Tech Details:
In `Clickatell\Api\ClickatellRest::sendMessage()` if there's an error, it is is saved to the response, but that is assigned without a `message` key. Then when it runs the `foreach ($response['message'] as $entry)` loop, the response has no message, so the `$return` remains an empty array and that's what's returned. Either the catch should assign a message to the response, or the catch should return response right there in the block.

**Comment by dpi** [comment]
This applies to HTTP as well.

The line inside `sendMessage()` should be changed from `$response = array(` to `return array(`

Ideally since the whole request failed the exception should not be caught, and let it bubble up. The other methods in the API files do not attempt to catch exceptions.

**Comment by dpi** [comment]
Also, the error code for each message is not being assigned:

`'errorCode'     => (isset($entry['code'])) ? $entry['error']['code'] : false`

The isset is missing a part of the array tree, it should be:

`'errorCode'     => (isset($entry['error']['code'])) ? $entry['error']['code'] : false`
