### ISSUE TITLE
Scheduled delivery

### ISSUE THREAD

**Issue by Ben-Atherton** [arcturial/clickatell#28]
Is it possible to add support for scheduled delivery please? https://archive.clickatell.com/developers/api-docs/scheduled-delivery-advanced-message-send/

Thanks

**Comment by arcturial** [comment]
All parameters are supported, you can just add the correct parameter as seen here: https://archive.clickatell.com/developers/api-docs/http-overview/

Add it to your 2D array when doing the sendMessage request.

If you are using the newer version, these values will be different. Please reference the Clickatell documentation for those.
