### ISSUE TITLE
Git branching & Composer

### ISSUE THREAD

**Issue by dpi** [arcturial/clickatell#29]
Do you think we can get separate branches for each of the major versions? Instead of developing on master?

Theres some docs on how Composer reads these versions: https://getcomposer.org/doc/articles/versions.md#branches

Tldr: Currently, you would have two branches: '2.1', and '3.0'

**Comment by arcturial** [comment]
Going to add two branches called 2.x and 3.x, master and the latest code in 3.x will still be synchronized though.

**Comment by arcturial** [comment]
Also, what would be the benefit in having a 3.x branch? I can see a use for it once version 4 is released, but now it would just be the same as master.

**Comment by dpi** [comment]
So we can set a dependency on dev-3.x, instead of dev-master. If master changes to be the equivalent of 4.x, then it will break older dependency declarations.
