### ISSUE TITLE
Can i send send bulk message?

### ISSUE THREAD

**Issue by mostafasoufi** [arcturial/clickatell#32]
Hi @Jonadabe ,

I'm not sure about this subject, Does the below code is work?

`$result = $clickatell->sendMessage(['to' => ['27111111111', '27111111112'], 'content' => 'Message Content']);`

**Comment by arcturial** [comment]
Yes that is meant to work, are you having issues with this? What response do you get?

**Comment by mostafasoufi** [comment]
Should be i check.
