### ISSUE TITLE
Use of `mo` parameter

### ISSUE THREAD

**Issue by mostafasoufi** [arcturial/clickatell#33]
Hi Guys,

Can i use of  `mo` parameter in the out request?
We need using the below parameters:
```
mo=1
from=YOURUSLONGNUMBER
```

**Comment by arcturial** [comment]
Yes

```
$clickatell->sendMessage(['to' => ['27111111111'], 'content' => 'Message Content', 'mo' => 1, 'from' => '1234']);
```

**Comment by mostafasoufi** [comment]
I have seen `sendMessage` method and I think the parameters should be passed to `$extra`

`public function sendMessage($to, $message, $extra = array())`

That right?

**Comment by mostafasoufi** [comment]
@arcadas 

Can you review my reply?
