### ISSUE TITLE
Using this package or from clickatell org?

### ISSUE THREAD

**Issue by Kyslik** [arcturial/clickatell#34]
Should we use https://github.com/arcturial/clickatell or https://github.com/clickatell/clickatell-php?

Also link to "issues" on the bottom of readme is broken (since on clickatell/clickatell-php issues are disabled).

**Comment by arcturial** [comment]
The package was started here and I maintain this as a personal copy since I am no longer employed at Clickatell. The package hosted on their account will probably receive future updates for new features more promptly (one would hope) and might also contain features not yet documented etc.

**Comment by Kyslik** [comment]
Ok, thanks :)
